Repository fourfourgo/fofogo, pull requests merged in 2023-08, with the labels that each got.

#7 🔖 [FEAT]: 작성한 문장을 원하는 언어로 번역한다.
  app/api/translate/text/route.ts
  validation/translate/text.validation.ts
Labels: 🎨 기능추가, 백앤드

#9 🔖 [FEAT] : 번역 API 및 mutation, debounce hook 추가
  APIs/translateApi.ts
  app/api/translate/text/route.ts
  components/chat-text.tsx
  components/chat-texts.tsx
  components/text-form.tsx
  components/ui/toast.tsx
  hooks/use-country.ts
  hooks/use-debounce.ts
  hooks/use-translate-text.ts
  validation/translate/text.validation.ts
Labels: 🎨 기능추가, 프론트앤드

#8 🔖 [FEAT]: 번역 내용 히스토리를 불러온다.
  app/api/translate/text/route.ts
  prisma/index-browser.js
  prisma/index.d.ts
  prisma/index.js
  prisma/schema.prisma
Labels: 🎨 기능추가, 백앤드

#10 🐛 FIX : 메세지에 언어 관계 설정으로 인한 api 오류 수정
  app/api/translate/text/route.ts
  prisma/index-browser.js
  prisma/index.d.ts
  prisma/index.js
  prisma/schema.prisma
Labels: 백앤드, 🐛 버그수정

#11 🔖 [FEAT] : navbar 레이아웃 위치 변경, logo icon 추가, speech 페이지 생성
  .pnp.cjs
  .yarn/cache/@radix-ui-react-avatar-npm-1.0.3-27b95608fe-defd6070ca.zip
  .yarn/cache/@radix-ui-react-scroll-area-npm-1.0.4-8a22706f83-f959006a73.zip
  .yarn/cache/@tanstack-match-sorter-utils-npm-8.8.4-488b98c113-d005f50075.zip
  .yarn/cache/@tanstack-react-query-devtools-npm-4.32.6-6d5e3b68d1-5a0686dfa0.zip
  .yarn/cache/@types-dom-speech-recognition-npm-0.0.1-abff49edcd-8b34af73c3.zip
  .yarn/cache/@types-react-speech-recognition-npm-3.9.2-a14ef62656-79b6f654df.zip
  .yarn/cache/copy-anything-npm-3.0.5-562d15fb3f-d39f6601c1.zip
  .yarn/cache/is-what-npm-4.1.15-328677a458-fe27f6cd4a.zip
  .yarn/cache/superjson-npm-1.13.1-39607ca2e6-9c8c664a92.zip
  .yarn/cache/use-sync-external-store-npm-1.2.0-44f75d2564-5c639e0f8d.zip
  APIs/translateApi.ts
  app/(root)/(route)/page.tsx
  app/(speech)/(route)/speech/page.tsx
  app/(speech)/layout.tsx
  app/api/translate/text/route.ts
  app/layout.tsx
  components/bot-avatar.tsx
  components/chat-text.tsx
  components/chat-texts.tsx
  components/navbar.tsx
  components/query-provider.tsx
  components/speech.tsx
  components/text-form.tsx
  components/ui/avatar.tsx
  components/ui/bot-avatar.tsx
  components/ui/scroll-area.tsx
  components/ui/user-avatar.tsx
  components/user-avatar.tsx
  hooks/use-country.ts
  hooks/use-history-text.ts
  hooks/use-translate-text.ts
  package.json
  public/fofogo.png
  public/fofogo_symbol.png
  yarn.lock
Labels: 프론트앤드, 📦 라이브러리 추가

#12 💄[STYLE]: 모바일 채팅화면 스크롤 고정 이슈 수정
  app/(root)/(route)/page.tsx
  app/(root)/layout.tsx
  app/layout.tsx
  components/navbar.tsx
  components/text-form.tsx
  tailwind.config.js
Labels: 프론트앤드, 💄 스타일

#14 🔖 [FEAT]: Web Speech Api 객체 정의
  .pnp.cjs
  .yarn/cache/@types-react-speech-recognition-npm-3.9.2-a14ef62656-79b6f654df.zip
  app/(root)/(route)/page.tsx
  hooks/use-voice.ts
  lib/Recorder.ts
  package.json
  test.js
  yarn.lock
Labels: 🎨 기능추가, 프론트앤드

#13 🔖 [FEAT] : popover 추가, 번역본 복사, texts 수정
  .pnp.cjs
  .yarn/cache/@radix-ui-react-popover-npm-1.0.6-e128999be1-fbe4264d0f.zip
  app/(speech)/(route)/speech/page.tsx
  components/audience-speech.tsx
  components/chat-text.tsx
  components/chat-texts.tsx
  components/my-speech.tsx
  components/navbar.tsx
  components/navigation-popover.tsx
  components/speech.tsx
  components/text-form.tsx
  components/ui/popover.tsx
  package.json
  yarn.lock
Labels: 🎨 기능추가, 프론트앤드, 📦 라이브러리 추가, 💄 스타일

#15 🔖 [FEAT]: 글로벌 로딩 추가
  .pnp.cjs
  .yarn/cache/@emotion-is-prop-valid-npm-0.8.8-261a0f2426-bb7ec6d48c.zip
  .yarn/cache/@emotion-memoize-npm-0.7.4-5648cf11b8-4e3920d4ec.zip
  .yarn/cache/@tanstack-query-core-npm-4.32.6-0762be2c4a-c06f4b8d7e.zip
  .yarn/cache/@tanstack-react-query-npm-4.32.6-a7de846a68-5ce7939515.zip
  .yarn/cache/broadcast-channel-npm-3.7.0-81ceba70bb-803794c48d.zip
  .yarn/cache/detect-node-npm-2.1.0-e8de0e94f7-832184ec45.zip
  .yarn/cache/framer-motion-npm-10.15.1-3ec30a2a4f-b8b08561d1.zip
  .yarn/cache/js-sha3-npm-0.8.0-decf3ddcfa-75df77c1fc.zip
  .yarn/cache/match-sorter-npm-6.3.1-ff3565ebb9-a4b02b676a.zip
  .yarn/cache/microseconds-npm-0.2.0-dbdb8ab8bb-22bfa8553f.zip
  .yarn/cache/nano-time-npm-1.0.0-6eca938be8-eef8548546.zip
  .yarn/cache/oblivious-set-npm-1.0.0-8e7336b241-f31740ea9c.zip
  .yarn/cache/react-query-npm-3.39.3-72b2a93edf-d2de6a0992.zip
  .yarn/cache/react-virtuoso-npm-4.5.0-98054907f2-5de2219642.zip
  .yarn/cache/unload-npm-2.2.0-c40df6b4d0-88ba950c5f.zip
  APIs/translateApi.ts
  app/(root)/(route)/page.tsx
  app/(root)/error.tsx
  app/(root)/layout.tsx
  app/api/translate/code-list/route.ts
  app/getQueryClient.tsx
  app/layout.tsx
  app/loading.tsx
  components/loading.tsx
  components/navigation-popover.tsx
  components/query-provider.tsx
  components/text-form.tsx
  components/ui/form.tsx
  hooks/use-country.ts
  hooks/use-history-text.ts
  hooks/use-translate-text.ts
  lib/Recorder.ts
  middleware.ts
  package.json
  yarn.lock
Labels: 🎨 기능추가, 프론트앤드, ❗️ 확인필요

#16 🔖 [FEAT] : 음성 번역 추가
  components/chat-texts.tsx
  components/navigation-popover.tsx
  components/text-form.tsx
Labels: 🎨 기능추가, 프론트앤드

#17 #17 🔖 [FEAT]: 메인 화면 리버스 스크롤 기능 추가
  APIs/translateApi.ts
  app/api/translate/text/route.ts
  components/chat-texts.tsx
  components/text-form.tsx
  hooks/use-history-text.ts
  hooks/use-voice.ts
  lib/Recorder.ts
  prisma/index-browser.js
  prisma/index.d.ts
  prisma/index.js
  prisma/schema.prisma
Labels: 🎨 기능추가, 프론트앤드, 백앤드

#18 #18 🔖 [FEAT]: 신규 메세지 생성 시 오토 스크롤 다운 기능 구현
  .pnp.cjs
  .yarn/cache/@types-uuid-npm-9.0.2-f2a5f65979-1754bcf344.zip
  APIs/translateApi.ts
  app/api/translate/text/route.ts
  app/layout.tsx
  components/chat-text.tsx
  components/chat-texts.tsx
  components/text-form.tsx
  hooks/use-translate-text.ts
  middleware.ts
  package.json
  yarn.lock
Labels: 🎨 기능추가, 프론트앤드, 📦 라이브러리 추가

#20 #20 🧪 [TEST] : 230815 QA 수정사항 적용
  .pnp.cjs
  .yarn/cache/@next-font-npm-13.4.16-356f53a9ff-12425ef1d2.zip
  .yarn/cache/react-spinners-npm-0.13.8-bf54f5b324-cb58f916bb.zip
  APIs/translateApi.ts
  app/(auth)/(route)/sign-in/[[...sign-in]]/page.tsx
  app/(speech)/(route)/speech/components/speech-inner.tsx
  app/(speech)/(route)/speech/page.tsx
  app/(speech)/layout.tsx
  app/PretendardVariable.woff2
  app/android-chrome-192x192.png
  app/apple-touch-icon.png
  app/browserconfig.xml
  app/favicon-16x16.png
  app/favicon-32x32.png
  app/favicon.ico
  app/getQueryClient.tsx
  app/globals.css
  app/layout.tsx
  app/mstile-150x150.png
  app/safari-pinned-tab.svg
  app/site.webmanifest
  components/audience-speech.tsx
  components/bot-avatar.tsx
  components/chat-text.tsx
  components/chat-texts.tsx
  components/mode-toggle.tsx
  components/my-speech.tsx
  components/navbar.tsx
  components/navigation-popover.tsx
  components/query-provider.tsx
  components/text-form.tsx
  components/ui/select.tsx
  hooks/use-voice.ts
  lib/Recorder.ts
  lib/headUtils.ts
  package.json
  prisma/index.js
  public/fofogo_favicon.png
  public/fofogo_logo.png
  public/fofogo_logotype_black.png
  public/fofogo_logotype_white.png
  public/next.svg
  public/vercel.svg
  tailwind.config.js
  yarn.lock
Labels: 🎨 기능추가, 프론트앤드, 🐛 버그수정, ❗️ 확인필요

#21 #21 🎨 feat : 대화형 페이지 기능 구현 완성
  .pnp.cjs
  .yarn/cache/asn1-npm-0.2.6-bdd07356c4-39f2ae343b.zip
  .yarn/cache/assert-plus-npm-1.0.0-cac95ef098-19b4340cb8.zip
  .yarn/cache/aws-sign2-npm-0.7.0-656c6cb84d-b148b0bb07.zip
  .yarn/cache/aws4-npm-1.12.0-af8e48a2ab-68f79708ac.zip
  .yarn/cache/bcrypt-pbkdf-npm-1.0.2-80db8b16ed-4edfc9fe7d.zip
  .yarn/cache/caseless-npm-0.12.0-e83bc5df83-b43bd4c440.zip
  .yarn/cache/core-util-is-npm-1.0.2-9fc2b94dc3-7a4c925b49.zip
  .yarn/cache/dashdash-npm-1.14.1-be8f10a286-3634c24957.zip
  .yarn/cache/ecc-jsbn-npm-0.1.2-85b7a7be89-22fef4b620.zip
  .yarn/cache/extsprintf-npm-1.3.0-61a92b324c-cee7a4a1e3.zip
  .yarn/cache/extsprintf-npm-1.4.1-140b2f27ab-a2f29b2419.zip
  .yarn/cache/forever-agent-npm-0.6.1-01dae53bf9-766ae6e220.zip
  .yarn/cache/form-data-npm-2.3.3-c016cc11c0-10c1780fa1.zip
  .yarn/cache/getpass-npm-0.1.7-519164a3be-ab18d55661.zip
  .yarn/cache/har-schema-npm-2.0.0-3a318c0ca5-d8946348f3.zip
  .yarn/cache/har-validator-npm-5.1.5-bd9ac162f5-b998a7269c.zip
  .yarn/cache/http-signature-npm-1.2.0-ee92426f34-3324598712.zip
  .yarn/cache/is-typedarray-npm-1.0.0-bbd99de5b6-3508c6cd0a.zip
  .yarn/cache/isstream-npm-0.1.2-8581c75385-1eb2fe63a7.zip
  .yarn/cache/jsbn-npm-0.1.1-0eb7132404-e5ff29c1b8.zip
  .yarn/cache/json-schema-npm-0.4.0-e776313070-66389434c3.zip
  .yarn/cache/json-stringify-safe-npm-5.0.1-064ddd6ab4-48ec0adad5.zip
  .yarn/cache/jsprim-npm-1.4.2-1ae6cade9a-2ad1b9fdcc.zip
  .yarn/cache/oauth-sign-npm-0.9.0-7aa9422221-8f5497a127.zip
  .yarn/cache/performance-now-npm-2.1.0-45e3ce7e49-534e641aa8.zip
  .yarn/cache/psl-npm-1.9.0-a546edad1a-20c4277f64.zip
  .yarn/cache/qs-npm-6.5.3-90b2635484-6f20bf08ca.zip
  .yarn/cache/request-npm-2.88.2-f4a57c72c4-4e112c087f.zip
  .yarn/cache/sshpk-npm-1.17.0-95f17f597f-ba109f65c8.zip
  .yarn/cache/supports-color-npm-9.4.0-a415f39758-cb8ff8daea.zip
  .yarn/cache/tough-cookie-npm-2.5.0-79a2fe43fe-16a8cd0902.zip
  .yarn/cache/tunnel-agent-npm-0.6.0-64345ab7eb-05f6510358.zip
  .yarn/cache/tweetnacl-npm-0.14.5-a3f766c0d1-6061daba17.zip
  .yarn/cache/uuid-npm-3.4.0-4fd8ef88ad-58de2feed6.zip
  .yarn/cache/verror-npm-1.10.0-c3f839c579-c431df0bed.zip
  APIs/common.ts
  APIs/translateApi.ts
  app/(root)/layout.tsx
  app/(speech)/(route)/speech/components/speech-inner.tsx
  app/api/translate/text/single/route.ts
  app/globals.css
  components/audience-speech.tsx
  components/mic-recorder.tsx
  components/my-speech.tsx
  components/navigation-popover.tsx
  components/text-form.tsx
  components/user-avatar.tsx
  lib/Recorder.ts
  package.json
  prisma/index.js
  validation/translate/text.validation.ts
  yarn.lock
Labels: 🎨 기능추가, 프론트앤드, 백앤드, 📦 라이브러리 추가
